# Generated by Django 5.2.6 on 2025-09-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agenda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Workshop', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='read_time',
            field=models.CharField(default='5 min read', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
